### ISSUE TITLE
Lost connection to device.

### ISSUE THREAD

**Issue by hadi7khan** [Hpaneru/camera_gallery_image_picker#3]
I am clicking pictures first time and it is working fine. When i try to use camera second time, app gets crashed and "Lost connection to device." is logged in terminal.

**Comment by johandb** [comment]
When I use the demo code I get an error, see below

**E/flutter ( 9843): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.image_picker_android.ImagePickerApi.pickImages"., null, null)
E/flutter ( 9843): #0      ImagePickerApi.pickImages (package:image_picker_android/src/messages.g.dart:337:7)
E/flutter ( 9843): <asynchronous suspension>
E/flutter ( 9843): #1      ImagePickerAndroid.getMultiImageWithOptions (package:image_picker_android/image_picker_android.dart:224:33)
E/flutter ( 9843): <asynchronous suspension>
E/flutter ( 9843): #2      CameraGalleryImagePicker.pickMultiImage (package:camera_gallery_image_picker/src/cameragalleryimagepicker.dart:155:41)**
